### ISSUE TITLE
Broken Nestjs 8.0 support

### ISSUE THREAD

**Issue by anakshiant** [nestjs/terminus#1452]
### I am submitting a...

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [X] Bug report
- [ ] Feature request
- [ ] Documentation issue or request

### Current behavior

If we import `TerminusModule` in our module context. it breaks with error

```
ERROR: Nest can't resolve dependencies of the TypeOrmHealthIndicator (?). Please make sure that the argument ModuleRef at index [0] is available in the TerminusModule context.

 Potential solutions:
 - If ModuleRef is a provider, is it part of the current TerminusModule?
 - If ModuleRef is exported from a separate @Module, is that module imported within TerminusModule?
   @Module({
    imports: [ /* the Module containing ModuleRef */ ]
   })

```

### Expected behavior

should not have any error.

### Minimal reproduction of the problem

```
@Module{}
export class AppModule {
   imports: [TerminusModule],
}
```
and then inject `TypeormHealthIndicator`  in any service.

### Terminus version

8.0.1

### NestJS version

8.0.7

**Comment by Tony133** [comment]
Hi @anakshiant, I suggest you create a minimal reproduction in a clonable git so you can better evaluate the problem.

However there is a working example [here](https://github.com/nestjs/terminus/tree/master/sample/005-typeorm-app).

**Comment by BrunnerLivio** [comment]
As @Tony133 mentioned, please create a minimal reproduction. I double-checked it locally and it does not break. I assume you may have imported the `TerminusModule` not in the right module?

**Comment by anakshiant** [comment]
turns out if you have a monorepo and you have two copies of nest js packages like `@nestjs/common, @nestjs/core` , we get `ModuleRef` injection error. 

solved this by removing duplicate package installation .

**Comment by AltarBeastiful** [comment]
I'm hitting the same error on a monorepo setup with multiple reference to @nestjs packages in my node_modules.
Is there any other workaround than removing the duplicates reference to @nestjs/common or @nestjs/core ?

My setup is 3 microservices in subprojects and I'm trying to do e2e testing running the 3 microservices together from the root directory.
For that I installed the subprojects in my root dir to include their depedencies. So my node_modules looks like :
* rootdir/
  * test-e2e/
  * node_modules/
    * @nestjs/common....
    * (symbolic link) microservice 1/
      * node_modules/
        * @nestjs/common... 
    * (symbolic link) microservice 2/
    * (symbolic link) microservice 3/

Is there anything I can do to keep my setup and use Terminus in my e2e tests ?

**Comment by JustDoItSascha** [comment]
I have the same problem, but I have only one reference of nestjs/common and nestjs/core. I'm also trying to use Terminus inside a library. My node_modules looks like this:

node_modules/
  my_library
    NO_NODE_MODULE!
  @nestjs
    core
    common
    terminus

But I'm also getting the same error. Any ideas that to do? I'm using terminus package 8.1.1

**Comment by Tony133** [comment]
Hi @JustDoItSascha  the package `nestjs/common`  and  `nestjs/core` they have the same version in the `package.json` ?

When you have time can you create a minimal reproduction in a clonable git of the problem?
