### ISSUE TITLE
pingCheck throws `TypeError: (0 , rxjs_1.lastValueFrom) is not a function` resulting in incorrect error detection

### ISSUE THREAD

**Issue by Shinigami92** [nestjs/terminus#1572]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When using pingCheck from `HttpHealthIndicator`

### Minimum reproduction code

```ts
this.http.pingCheck('google', 'https://google.com')
```

### Steps to reproduce

Create a project with this `pingCheck` and add a `console.log(err);` in the `pingCheck` function. Otherwise the error will not be shown and is therefore invisible!

It might be interesting that we use `rxjs@7.4.0` in `package.json` 🤔 I'm not sure if this affects this in any way.

### Expected behavior

It should handle errors like `responseCheck`

### Package version

8.0.1

### NestJS version

8.2.3

### Node.js version

16.13.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Other

When adding `console.log(err);` in `<projectPath>/node_modules/@nestjs/terminus/dist/health-indicator/http/http.health.js` Line 120 (between ` catch (err) {` and `this.generateHttpError(key, err);`) you can see:

```node
TypeError: (0 , rxjs_1.lastValueFrom) is not a function
    at HttpHealthIndicator.<anonymous> (<projectPath>/node_modules/@nestjs/terminus/dist/health-indicator/http/http.health.js:116:48)
    at Generator.next (<anonymous>)
    at <projectPath>/node_modules/@nestjs/terminus/dist/health-indicator/http/http.health.js:17:71
    at new Promise (<anonymous>)
    at __awaiter (<projectPath>/node_modules/@nestjs/terminus/dist/health-indicator/http/http.health.js:13:12)
    at HttpHealthIndicator.pingCheck (<projectPath>/node_modules/@nestjs/terminus/dist/health-indicator/http/http.health.js:108:16)
    at health.check.dns.responseCheck.status.status (<projectPath>/src/endpoints/health/health.controller.ts:19:28)
    at HealthCheckExecutor.<anonymous> (<projectPath>/node_modules/@nestjs/terminus/dist/health-check/health-check-executor.service.js:66:42)
    at Generator.next (<anonymous>)
    at <projectPath>/node_modules/@nestjs/terminus/dist/health-check/health-check-executor.service.js:14:71
```

**Comment by Shinigami92** [comment]
Found out that rxjs is a peer dep as 7.x

https://github.com/nestjs/terminus/blob/3b5e056a3ddbafadcd7eb344ec89236ca3c616c7/package.json#L103

If there was a breaking change in one of the minor versions, this could be a reason 🤔

**Comment by Shinigami92** [comment]
Further note: seems that

https://github.com/nestjs/terminus/blob/3b5e056a3ddbafadcd7eb344ec89236ca3c616c7/lib/health-indicator/http/http.health.ts#L119-L124

differs much from

https://github.com/nestjs/terminus/blob/3b5e056a3ddbafadcd7eb344ec89236ca3c616c7/lib/health-indicator/http/http.health.ts#L155-L169

Not sure if this is wanted. When using the `pingCheck` it returns `"down"`, but `status` is still `"ok"`, where as with `responseCheck` the `status` is `"error"` due to that a `HealthCheckError` is correctly thrown.

**Comment by Tony133** [comment]
Hi @Shinigami92, you took a look at this example: https://github.com/nestjs/terminus/tree/master/sample/009-http-app ?

**Comment by Shinigami92** [comment]
Now yes, only difference I can see is that it explicitly use rxjs 7.3 instead of 7.4

https://github.com/nestjs/terminus/blob/5b7c2a8de28d450328b5bdb89f6e99d7b75a089d/sample/009-http-app/package.json#L25

**Comment by Tony133** [comment]
@Shinigami92, I tried to install the rxjs dependency with version 7.4.0 in the example I told you above and it doesn't give me any error

**Comment by Shinigami92** [comment]
If I remember correctly, yes I tried that and also completely clean node_modules and everything
Our team decided (sadly) that we don't need the health module anyways, so I removed it completely :shrug: 
So I don't have a reprogression anymore :confused: 

You can close the issue if you want to, but see it as a notification if it come up again from other users

**Comment by Tony133** [comment]
@Shinigami92, yes, surely it can be useful in the future if other people experience this problem. If you want you can close this issue., unfortunately I do not have the permissions to close this problem. Maybe I will have them in the future who knows. 

However if you have any difficulties or doubts in the future remember that you can always use the [Discord](https://discord.com/invite/G7Qnnhy) support channel. 😉👍
