### ISSUE TITLE
responseCheck "URL" type is undefined

### ISSUE THREAD

**Issue by rudemex** [nestjs/terminus#1620]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I am building a centralized healtcheks module, but the URL data type is not defined and it breaks the build with pika.

![image](https://user-images.githubusercontent.com/1771743/149535333-68245ff7-319d-4882-96be-5a231981ceba.png)

### Minimum reproduction code

```ts
-
```

### Expected behavior

 add `import { URL } from 'url';` in this file https://github.com/nestjs/terminus/blob/master/lib/health-indicator/http/http.health.ts

### Package version

8.0.3

### NestJS version

8.2.5

### Node.js version

14.15.4

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by Tony133** [comment]
Hi @rudemex , I advise you to leave a minimal reproduction of a clonable git repository so that the NestJS core team can evaluate the problem you have reported.

**Comment by rudemex** [comment]
Move this issue to https://github.com/nestjs/terminus/issues/1623
