### ISSUE TITLE
Cannot find name 'URL' - type url is not imported in responseCheck (health-indicator/http/http.health.ts)

### ISSUE THREAD

**Issue by rudemex** [nestjs/terminus#1623]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I am building a centralized healtcheks module, but the URL data type is not defined and it breaks the build with pika.

![image](https://user-images.githubusercontent.com/1771743/149583340-ba7e6645-6df3-4d69-94d9-554937434369.png)

### Minimum reproduction code

1. git clone https://github.com/tresdoce/nestjs-health.git
2. git checkout feat/update
3. npm install
4. npm run build
5. see the error
```
...
[3/6] Running @pika/plugin-ts-standard-pkg...
node_modules/@nestjs/terminus/dist/health-indicator/http/http.health.d.ts(51,40): error TS2304: Cannot find name 'URL'.
...
```

### Steps to reproduce

1. git clone https://github.com/tresdoce/nestjs-health.git
2. git checkout feat/update
3. npm install
4. npm run build
5. see the error
```
...
[3/6] Running @pika/plugin-ts-standard-pkg...
node_modules/@nestjs/terminus/dist/health-indicator/http/http.health.d.ts(51,40): error TS2304: Cannot find name 'URL'.
...
```

### Expected behavior

add `import { URL } from 'url';` in this file https://github.com/nestjs/terminus/blob/master/lib/health-indicator/http/http.health.ts

### Package version

8.0.3

### NestJS version

8.2.5

### Node.js version

14.15.4

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by BrunnerLivio** [comment]
Fixed with [8.0.4](https://github.com/nestjs/terminus/releases/tag/8.0.4) 🎉
