### ISSUE TITLE
Elasticsearch health-indicator

### ISSUE THREAD

**Issue by stanimirovv** [nestjs/terminus#1716]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

I am interested in creating and maintaining a health-indicator for elasticsearch.

I realise you can use the http indicator for it, in fact one of the examples is for it:
https://github.com/nestjs/terminus/pull/985

However I think there is value to be added by having a stand alone elasticsearch indicator:
- make authentication easier
- offer option for both cluster and index level monitoring

That being said - with the base http-indicator it is quite doable. I am not sure what is the intent - have several very generic indicators or also have specific ones ?

Cheers!

### Describe the solution you'd like

elasticsearch health-indicator

### Teachability, documentation, adoption, migration strategy

Not applicable

### What is the motivation / use case for changing the behavior?

Elasticsearch is very popular and having a streamlined standartized way that is extendable will be helpful to a lot of people.

Also I think it is fine since there is an official nestjs ES client.

**Comment by stanimirovv** [comment]
@kamilmysliwiec does this sound like something that can be added or maybe should be a stand alone plugin/package ?

**Comment by rubiin** [comment]
I think you can make one yourself. Heres a sample https://github.com/nestjs/terminus/blob/master/sample/000-dogs-app/src/dog/dog.health.ts for custom health check

**Comment by stanimirovv** [comment]
Agreed, it is most likely the cleaner way since less code to maintain in nest.

**Comment by rubiin** [comment]
Yeah this custom stuffs is where nestjs shines.
