### ISSUE TITLE
Allow to pass terminus options

### ISSUE THREAD

**Issue by raphaelbadia** [nestjs/terminus#1791]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

I would like to define the grace period before the server actually gets killed by kubernetes

### Describe the solution you'd like

I would like to pass the `beforeShutdown` to terminus so I can use the gracePeriod defined in kubernetes.

### Teachability, documentation, adoption, migration strategy

```
@Module({
  imports: [TerminusModule.config(options), ArticlesModule], // like this ?
  controllers: [HealthController],
})
```

### What is the motivation / use case for changing the behavior?

When using terminus with express js, we use the beforeShutdown hook to delay the shutdown, waiting for an arbitrary `gracePeriod` (https://github.com/godaddy/terminus) . This is recommended with kubernetes. 

```typescript
type GracefulOptsType = {
  readinessFailure: number;
  readinessPeriod: number;
};
const graceful = (
  server: Server,
  { readinessFailure, readinessPeriod }: GracefulOptsType, // from kubernetes 
) => {
  createTerminus(server, {
    healthChecks: {
      // @ts-ignore
      '/healthcheck': ({ state }: { state: any }) => {
        if (state.isShuttingDown) {
          console.error('Shutting down');
          return Promise.reject(new Error('Shutting down'));
        }
        return Promise.resolve('Healthy');
      },
    },
    signals: ['SIGTERM', 'SIGINT'],
    beforeShutdown: () => {
      console.info(
        'Got SIGTERM. Graceful shutdown start at',
        new Date().toISOString(),
      );
      return new Promise(resolve => {
        const gracefulStopDelay = readinessFailure * readinessPeriod;
        setTimeout(resolve, gracefulStopDelay * 1000);
      });
    },
  });
};
```

**Comment by BrunnerLivio** [comment]
Hey @raphaelbadia. I actually implemented this, but added it as Lifecycle to NestJS core itself. I believe [beforeApplicationShutdown or onApplicationShutdown](https://docs.nestjs.com/fundamentals/lifecycle-events#application-shutdown) should aid you with this!

**Comment by raphaelbadia** [comment]
Thanks !

Le mer. 20 avr. 2022 à 07:52, Livio Brunner ***@***.***> a
écrit :
