### ISSUE TITLE
Add MikroOrm health indicator

### ISSUE THREAD

**Issue by jbw** [nestjs/terminus#1877]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

There is no way to health check using MikroOrm. 

### Describe the solution you'd like

I want to health check using MikroOrm. 

### Teachability, documentation, adoption, migration strategy

.

### What is the motivation / use case for changing the behavior?

.

**Comment by BrunnerLivio** [comment]
[Released with 8.1.0](https://github.com/nestjs/terminus/releases/tag/8.1.0) 🎉 
Thanks!
