### ISSUE TITLE
Sample code for Redis healthcheck does not work

### ISSUE THREAD

**Issue by soracha** [nestjs/terminus#1948]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Sample code for Redis healthcheck in [002-microservice-app](https://github.com/nestjs/terminus/tree/08c0de9976c73e8d665b1f4c8a9976cb1fc02f51/sample/002-microservice-app) always return status `down` even I can connect the server via Redis GUI

### Minimum reproduction code

```ts
return this.health.check([
      async () =>
        this.microservice.pingCheck(`redis`, {
          transport: Transport.REDIS,
          options: {
            host: REDIS_HOST,
            port: REDIS_PORT,
          },
        }),
    ]);
```

The result
```
{
    "status": "error",
    "info": {},
    "error": {
        "redis": {
            "status": "down",
            "message": "Connection is closed."
        }
    },
    "details": {
        "redis": {
            "status": "down",
            "message": "Connection is closed."
        }
    }
}
```

### Expected behavior

Return Redis server status as it is

### Package version

9.00

### NestJS version

8.4.6

### Node.js version

16.14.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by Tony133** [comment]
see this PR: https://github.com/nestjs/terminus/pull/1954

**Comment by BrunnerLivio** [comment]
We should go with 6379 since that is the default port and the one we use in our[docker-compose.yml file as well](https://github.com/nestjs/terminus/blob/139eca6fea4c7a8eeae1d5676b0b0272ac6c84c7/sample/002-microservice-app/docker-compose.yml#L8).
