### ISSUE TITLE
Bug:  Healthcheck Failures Do Not Work as Expected

### ISSUE THREAD

**Issue by iMerica** [nestjs/terminus#1960]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Hi, I'm testing your library to ensure the failure states work properly by creating a health check I expect to return as "down" or failing and instead of responding immediately that the status is down, the health check just times out. This happens for both memory heap and rss checks.

### Minimum reproduction code

```ts

MAX_ALLOCATION  = 25
@Controller('health')
export class HealthController {
  constructor(
    private health: HealthCheckService,
    private memory: MemoryHealthIndicator,
  ) {}

  @Get()
  @HealthCheck()
  check(): unknown {
    return this.health.check([
      (): Promise<HealthIndicatorResult> =>
        this.memory.checkHeap('memory_heap', MAX_ALLOCATION * 1024 * 1024),
    ]);
  }
}

```

### Steps to reproduce

- Create a new memory healthcheck that you would expect to fail, like that the process consumes less than 25 MB of memory
```jsx
      (): Promise<HealthIndicatorResult> =>
        this.memory.checkHeap('memory_heap',  25 * 1024 * 1024),
    ]);
```

- Start the server and perform a GET request to `/health/`
- Observe that instead of an immediate failure response (HTTP 200 with a negative payload or some other HTTP code with the payload), we see the server stall out until a timeout occurs
- Update the health check to use a value of memory you expect will pass (e.g < 800MB) and the server responds as expected:
```json
{
  "status": "ok",
  "info": {
  "db": {
  "status": "up"
},
"memory_heap": {
"status": "up"
}
},
  "error": {},
  "details": {
  "db": {
  "status": "up"
},
  "memory_heap": {
  "status": "up"
}
}
}
```

### Expected behavior

I expect the library to return a failure state instead of timing out. Like all other healthcheck tools work in other web frameworks. 

### Package version

^9.0.0

### NestJS version

8.0.0

### Node.js version

16

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [X] Linux

**Comment by iMerica** [comment]
For more context, this is what I'm seeing in my logs:

```
[Nest] 68824  - 07/24/2022, 2:36:59 PM   ERROR [HealthCheckService] Health Check has failed! {"memory_heap":{"status":"down","message":"Used heap exceeded the set threshold"}}

```

**Comment by BrunnerLivio** [comment]
@iMerica I’ll get back to this once I am back from vacation 🏝

**Comment by BrunnerLivio** [comment]
@iMerica I can not reproduce this issue.

Here is the version I am using (should be the same as yours)

```bash
$ nest info

...

[System Information]
OS Version     : Linux 4.15
NodeJS Version : v16.16.0
NPM Version    : 8.11.0
[Nest Information]
platform-express version : 8.4.7
terminus version         : 9.0.0
common version           : 8.4.7
core version             : 8.4.7
```

This is my health check:

```typescript
@Get()
@HealthCheck()
healthCheck() {
  return this.health.check([
    async () => this.memory.checkHeap('memory_heap', 25 * 1024 * 1024),
  ]);
}
```

Result:

```json
curl -s localhost:3000/health | jq
{
  "status": "error",
  "info": {},
  "error": {
    "memory_heap": {
      "status": "down",
      "message": "Used heap exceeded the set threshold"
    }
  },
  "details": {
    "memory_heap": {
      "status": "down",
      "message": "Used heap exceeded the set threshold"
    }
  }
}
```

Therefore I'd need more information and/or minimal reproduction (preferably in a docker container)
