### ISSUE TITLE
After PR #1970 (update from 9.0.0 to 9.1.0) there is an error with TERMINUS_ERROR_LOGGER

### ISSUE THREAD

**Issue by bintoll** [nestjs/terminus#1974]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Application does not start with error:

`Nest can't resolve dependencies of the HealthCheckService (HealthCheckExecutor, ?). Please make sure that the argument TERMINUS_ERROR_LOGGER at index [1] is available in the HealthModule context`

### Minimum reproduction code

Please check the repo: https://github.com/bintoll/nest-terminus-error-reproduction

### Steps to reproduce

1. yarn install 2. yarn start

### Expected behavior

THe app starts as usual before PR #1970 as in 9.0.0

### Package version

9.1.0

### NestJS version

8.0.0

### Node.js version

16.14.2

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by BrunnerLivio** [comment]
Thanks for your submission. In your minimal reproduction, you are adding the `HealtCheckService` and `HealthCheckExecutor` as providers. Simply remove these and it works as expected. Not sure why you've added them in the first place -- to my knowledge no documentation should mention this?

```diff
@Module({
  imports: [TerminusModule],
  controllers: [HealthController],
-  providers: [HealthCheckService, HealthCheckExecutor],
})
```

**Comment by bintoll** [comment]
You are right, after removing it everything is fine. Strange thing that I added this most likely because of other errors that nest produced previously. Thank you! And sorry for raising an issue.
