### ISSUE TITLE
NestJS Terminus has an undeclared dependency on Axios

### ISSUE THREAD

**Issue by osidenate** [nestjs/terminus#1991]
### Did you read the migration guide?

- [X] I have read the whole migration guide

### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Versions

8.0.6 -> 9.1.0

### Describe the regression

There is a new dependency on `axios` from a type definition file.

<img width="773" alt="axios-import-error" src="https://user-images.githubusercontent.com/497417/184026330-9094efc9-38f6-4ce4-9c2b-af37642f2ba0.png">

The dependency is not specified in the package.json. Including `@nestjs/axios` as a peerDependency may help resolve this.

### Minimum reproduction code

```ts

```

### Expected behavior

Should be able to reference `@nestjs/terminus` without having to install axios directly.

**Comment by BrunnerLivio** [comment]
Fixed with[ 9.1.1](https://github.com/nestjs/terminus/releases/tag/9.1.1)!
