### ISSUE TITLE
this library does not support Nestjs 10.0.0

### ISSUE THREAD

**Issue by xuegao-tzx** [nestjs/terminus#2277]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

this library does not support Nestjs 10.0.0

### Minimum reproduction code

```ts
this library does not support Nestjs 10.0.0
```

### Expected behavior

this library does not support Nestjs 10.0.0

### Package version

9.2.2

### NestJS version

10.0.0

### Node.js version

18.16.0

### In which operating systems have you tested?

- [X] macOS
- [X] Windows
- [X] Linux

### Other

this library does not support Nestjs 10.0.0

**Comment by Tony133** [comment]
Hi @xuegao-tzx,  check this out: https://github.com/nestjs/terminus/releases/tag/10.0.0-beta.0

In the meantime the final version is published, do this:

 `npm install @nestjs/terminus@10.0.0-beta.0`

if you really want to try it out with NestJS v10 🚀

A word of advice, always wait a few days before updating to new versions so that all packages are compatible. NestJS v10 is out today so it takes a couple of days before everything is compatible. 🙌

I hope i was helpful

**Comment by tsabolov** [comment]
> Hi @xuegao-tzx, check this out: https://github.com/nestjs/terminus/releases/tag/10.0.0-beta.0
> 
> In the meantime the final version is published, do this:
> 
> `npm install @nestjs/terminus@10.0.0-beta.0`
> 
> if you really want to try it out with NestJS v10 🚀
> 
> A word of advice, always wait a few days before updating to new versions so that all packages are compatible. NestJS v10 is out today so it takes a couple of days before everything is compatible. 🙌
> 
> I hope i was helpful

Unfortunately, the beta build does not help, because it declares now-outdated [peer dependencies](https://github.com/nestjs/terminus/blob/10.0.0-beta.0/package.json#L114-L115). Anyway, thank you for the advice to wait a couple of days 😉

**Comment by Tony133** [comment]
> > CIAO@xuegao-tzx, dai un'occhiata a questo: https://github.com/nestjs/terminus/releases/tag/10.0.0-beta.0
> > Nel frattempo viene pubblicata la versione finale, procedere come segue:
> > `npm install @nestjs/terminus@10.0.0-beta.0`
> > se vuoi davvero provarlo con NestJS v10🚀
> > Un consiglio, aspetta sempre qualche giorno prima di aggiornare alle nuove versioni in modo che tutti i pacchetti siano compatibili. NestJS v10 è uscito oggi, quindi ci vogliono un paio di giorni prima che tutto sia compatibile.🙌
> > Spero di essere stato d'aiuto
> 
> Sfortunatamente, la build beta non aiuta, perché dichiara [dipendenze peer](https://github.com/nestjs/terminus/blob/10.0.0-beta.0/package.json#L114-L115) ormai obsolete . Comunque grazie per il consiglio di aspettare un paio di giorni😉

Yes it's true, I was convinced it already had the dependencies for v10, my mistake 🙏🏻, however you will see that the update will arrive soon 😉. It takes some patience. 😄

**Comment by BrunnerLivio** [comment]
I am preparing the release, if everything goes according to plan I should be able to release in a couple of hours!

#2282

**Comment by BrunnerLivio** [comment]
[It's here 🎉  ](https://github.com/nestjs/terminus/releases/tag/10.0.0)

MikrOrm users might see a a legacy peer deps error when using `npm install`. This is because `@mikro-orm/nestjs` has not been updated to NestJS v10
https://github.com/mikro-orm/nestjs/issues/122
