### ISSUE TITLE
MongooseHealthIndicator fail with a connection name

### ISSUE THREAD

**Issue by Mualig** [nestjs/terminus#289]
## I'm submitting a...
<pre><code>
[ ] Regression 
[X] Bug report
[ ] Feature request
[X] Documentation issue or request
[ ] Support request
</code></pre>

## Current behavior
When using MongooseHealthIndicator, if MongooseModule is used with the `connectionName` option (because I have two mongoose connections):
```
MongooseModule.forRoot(resourcesUri, { useNewUrlParser: true, connectionName: 'resources' }),
```
The health check will fail even if I'm using the `connection` option:
```
healthIndicators: [
  async () => await this.mongoose.pingCheck('mongo', { connection: 'resources' }),
],
```
Health check response: HTTP 503
```
{
  "status": "error",
  "error": {
    "memory_heap": {
      "status": "up"
    },
    "memory_rss": {
      "status": "up"
    },
    "mongo": {
      "status": "down"
    }
  },
  "details": {
    "memory_heap": {
      "status": "up"
    },
    "memory_rss": {
      "status": "up"
    },
    "mongo": {
      "status": "down"
    }
  }
}
```

## Expected behavior
```
    "mongo": {
      "status": "up"
    }
```
Since the other routes using this connection are working.

## Minimal reproduction of the problem with instructions
See current behavior

## What is the motivation / use case for changing the behavior?
I want to be able to specify the `connectionName` and have a correct health check response.

## Environment

<pre><code>
Nest version: 6.5.2
Terminus version: 4.1.2
NestJS terminus version: 6.5.0
 
For Tooling issues:
- Node version: 10.16.0
- Platform:  Linux, Docker
</code></pre>

**Comment by BrunnerLivio** [comment]
You have to use the connection object instead of the connection name. 

If you provide the `TerminusOptions` with `useClass`, then you can do this:

```ts
import { Connection } from 'mongoose';
import { InjectConnection } from '@nestjs/mongoose';

export class TerminusOptionsService implements TerminusOptionsFactory {
  constructor(
    @InjectConnection('resources') private readonly conncetion: Connection
  ) {}

  public createTerminusOptions(): TerminusModuleOptions {
    const healthEndpoint: TerminusEndpoint = {
      url: '/health',
      healthIndicators: [
        async () => this.mongoose.pingCheck('mongo', { connection: this.connection }),
...

```

with a factory:

```ts
import { Connection } from 'mongoose';
import { getConnectionToken } from '@nestjs/mongoose';


const getTerminusOptions = (
  mongoose: MongooseHealthIndicator,
  connection: Connection
): TerminusModuleOptions => ({
  endpoints: [
    {
      url: '/health',
      healthIndicators: [async () => await mongoose.pingCheck('mongo', { connection })],
    },
  ],
});

@Module({
  imports: [
    MongooseModule.forRoot(resourcesUri, { useNewUrlParser: true, connectionName: 'resources' }),
    TerminusModule.forRootAsync({
      inject: [MongooseHealthIndicator, getConnectionToken('resources')],
      useFactory: getTerminusOptions,
    }),
...
```

**Comment by Mualig** [comment]
It works perfectly, thanks.
