### ISSUE TITLE
graceful shutdown

### ISSUE THREAD

**Issue by loveloper44** [nestjs/terminus#40]
Hi I'm Ingyu Yoon

These days, I have studied graceful shutdown and I want to use terminus in my nest app.
and I got to know this lib after searching. 
I think this library doesn't provide onShutdown callback function like terminus.
Could you tell me why you didn't support that options?

**Comment by BrunnerLivio** [comment]
Thanks for your issue. Yes I intentionally did not use the feature from the original lib and implemented it into the core of NestJs 6.0.0 as a lifecycle hook:

main.ts
```ts
async function bootstrap() {
  const app = await NestFactory.create(AppModule, { logger: true });
     // Listen to all shutdown hooks (e.g “SIGTERM” “SIGINT”
    app.enableShutdownHooks();
    // only listens to SIGINT
    // app.enableShutdownHooks([‘SIGINT’]); 
  }

  await app.listen(1800);
  process.kill(process.pid, SIGNAL);
}

bootstrap();

```

any injectable:

```ts
@Injectable()
class TestInjectable implements OnApplicationShutdown {
  onApplicationShutdown(signal: string) {
    console.log('Signal ' + signal);
  }
}
```

Does this implementation statisfy your requirements?

My example may won’t work because you need to migrate to 6.0.0 and `@nestjs/terminus` hasn’t been upgraded yet. So TL;DR it will come with the 6.0.0 release :)

**Comment by loveloper44** [comment]
Oh, I got it. It's cool. But we need the feature right now for our service. so I made the "nest-graceful" library and deployed to npm.

**Comment by BrunnerLivio** [comment]
@loveloper44 6.0.0 has been published -- Doc update are pending: [docs.nestjs.com#267](https://github.com/nestjs/docs.nestjs.com/pull/267) [docs.nestjs.com#266](https://github.com/nestjs/docs.nestjs.com/pull/266)

**Comment by ZanMinKian** [comment]
Well, actually, when client's http request headers includes `Connection: keep-alive`, request from new http connection will be refused. But it will not refuse connection which established. The  app will not shutdown if client request frequently using established connection.

**Comment by hienngm** [comment]
I agree that when clients frequently use an established connection with the `Connection: keep-alive` header, it can cause your server to hang indefinitely. To resolve this issue, I developed the [`nestjs-graceful-shutdown`](https://www.npmjs.com/package/nestjs-graceful-shutdown) package, which is powered by [`http-terminator`](https://www.npmjs.com/package/http-terminator) library. I hope it's useful to you.
